### ISSUE TITLE
doc doctests fail on Python 3

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#10]
Running `make doctest` in the doc dir fails on Python 3 because the doc uses `print` statements instead of function calls.

**Comment by bastikr** [comment]
I saw you already fixed that in your repository. Can you maybe rebase onto the latest master branch? I also added you as collaborator so you can push yourself when the patch is ready.

**Comment by pombredanne** [comment]
Yes, I already fix that and will rebase and push as a separate branch

**Comment by bastikr** [comment]
Okay this works now.
