### ISSUE TITLE
bool(FALSE) should be False

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#12]
From @Kronuz in #7 :
> First, bool(TRUE) could also be (and currently) is True, but bool(FALSE) should, I think, also be False, but it isn't. I added __bool__() (and __nozero__() for Python 2) to TRUE and FALSE classes.

**Comment by bastikr** [comment]
That change is fine, but when we implement this for TRUE and FALSE we maybe should also think about what bool(Expression) should be. At the moment it returns True but I think it should either return None or even raise an exception to prevent mistakes.

**Comment by pombredanne** [comment]
@bastikr to determine what `bool(Expression)` should be, __nonzero__ must be defined and really evaluate the expression? Do you have code that does that? It may also have some ripple effects elsewhere IMHO

**Comment by bastikr** [comment]
In my opinion we can't give `bool(Expression)`  a meaningful value. At the moment it uses the default python implementation and return True. I would raise some kind of exception instead.

**Comment by Kronuz** [comment]
Yes, maybe an exception would be good; but it should try simplifying itself before raising an exception, to see if the expression is actually True/False already, if not, should complain about not being able to evaluate as boolean. for example in this case:

```python
a, b = boolean.symbols("a", "b")
expr = boolean.parse("a+c", simplify=False).subs({a: boolean.TRUE}, simplify=False)
```
I would argue Expression should first try to simplify stuff so `bool(expr)` would be `True`. I'll make a PR.

**Comment by bastikr** [comment]
This is merged. Closing.
