### ISSUE TITLE
Undefined item variable

### ISSUE THREAD

**Issue by Kronuz** [bastikr/boolean.py#21]
In https://github.com/bastikr/boolean.py/blob/master/boolean/boolean.py#L860:

```python
if all(arg in self.args for arg in item.args):
    args = tuple(arg for arg in self.args if arg not in expo)
```
It uses an undefined variable `item`. What is this supposed to do?

I just removed the `all()` test, leaving only this:

```python
args = tuple(arg for arg in self.args if arg not in expo)
```

But I'm not sure what that check was intended for (originally).

**Comment by pombredanne** [comment]
not sure either, but this LGTM

**Comment by bastikr** [comment]
It should be expr instead of item but I'm too tired at the moment to understand why this is necessary. Let me think about this again before pushing.

**Comment by bastikr** [comment]
The difference is the following:

```python
    >> expr = boolean.parse("a*b*c")
    >> pattern = boolean.parse("a*b*k")
    >> print(expr.remove(pattern))
    # with all test
    a*b*c
    # without all test
    c
```
So the line is definitely needed. I will fix and push it.

**Comment by bastikr** [comment]
It is fixed now.
