### ISSUE TITLE
Normal forms?

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#24]
@bastikr I see this old commit https://github.com/bastikr/boolean.py/commit/d6f169e7ee39244feb3cd89730591fbed9b17872
I wonder if you had plans to re-instate some of it? or?
In particular there is code for minimization.... yummy

**Comment by bastikr** [comment]
This code is only a faint memory :P. I definitely wouldn't implement separate classes for normal forms and calculating Expressions that are normal can already be done in boolean.py. The minimization would probably be useful. As far as I remember I implemented the Quine-McCluskey algorithm but I don't remember if it worked. What I see from this old commit that it contained a lot of ugly code. If we end up reimplementing it we should maybe put it into a separate file.

**Comment by pombredanne** [comment]
We have `normalize` alright. we can build CNF and DNF alright with it.
