### ISSUE TITLE
Publish in pypi

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#26]
@bastikr now that you have a proper setup, you could push to Pypi... Or I can handle it. Your call
@rossant recently released `pipo` a tool supposed this real easy: https://github.com/rossant/pipo/ and https://pypi.python.org/pypi/pipo/

**Comment by bastikr** [comment]
I would be very grateful if you could do it! Even though I already submitted something to Pypi once I would have to read up the details again. So thank you! I just checked and for me all tests pass for python 2 and 3 and also the doctest are fine - it should be ready to push.

**Comment by Kronuz** [comment]
Maybe we should wait to have the new tokenizer. This all is coming pretty nicely together, we'll have a solid first PyPI release! I'm excited.

**Comment by pombredanne** [comment]
@bastikr I will handle it
@Kronuz yes we should wait a bit, though releasing early is not an issue with proper warnings

**Comment by pombredanne** [comment]
@bastikr if I handle it you will have to give me access to RTD for the doc publishing at http://readthedocs.org/docs/booleanpy/en/latest/

**Comment by bastikr** [comment]
I just added a webhook so RTD should update automatically but I din't try it out yet. Is your username on RTD the same as on github? I'll add you as maintainer. @Kronuz you also want to have access? Btw I also added you as collaborator for boolean.py so you should have push access.

**Comment by Kronuz** [comment]
@bastikr, thank you! Sure, that access could help if something needs to be updated/changed; access doesn't hurt.

**Comment by pombredanne** [comment]
@bastikr you wrote:
> Is your username on RTD the same as on github? I'll add you as maintainer

Yes: pombredanne

**Comment by bastikr** [comment]
Okay I added you both.

**Comment by Kronuz** [comment]
@bastikr, thank you!

**Comment by pombredanne** [comment]
I pushed a first release 1.2 on Pypi!
No updated docs though, but also a minimal README update.
To push a new release:
1. Update the  version in setup.py commit and push a tag on that.
2. Assuming you have a proper `.pypirc` file with
```
[distutils]
index-servers =
    pypi

[pypi]
username:YOUR USER
password:YOUR PASSWORD
```

You can then do:
`python setup.py release` and you are done

**Comment by pombredanne** [comment]
See https://pypi.python.org/pypi/boolean.py

**Comment by bastikr** [comment]
Very nice! Good job everyone!

**Comment by pombredanne** [comment]
actually it sounds like the doc is built on commit and on tags automagically thanks to the webhook
So this can be closed
