### ISSUE TITLE
On BooleanAlgebra and design

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#30]
@bastikr It dawned on me that there is a little used object called BooleanAlgebra?

I am not sure I grok entirely its purpose, but it seems to have been designed as a central configuration and entry point.
In particular it holds the base elements for `TRUE` and `FALSE` and the default `Symbol` class.
I wonder if we should use this class more and instead of passing a `symbol_class` to `parse`, passing it an algebra.
Also we could have it hold the strings to use for `__str__` and `__repr__` for operators, parens, etc. I very much want and need to have  custom serializations that would not use the default `*+~`.
Also the parse function could become also a method of this?

So a custom algebra is something where you could redefine what is the parsing or tokenization logic,what are the base elements, the Symbol class to use and how expressions are serialized. 

I am just throwing out some ideas, but there is a few quirks in the current design that tickle me.

@Kronuz you take is appreciated too

**Comment by pombredanne** [comment]
I cannot really articulate it but there something that feels not right between here:
* https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L25
* https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L52
* https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L362
And here:
https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L952
and here: https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L1001

The algebra definition is entirely ignored here: https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L1061 and here https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L1083 

So I think that @Kronuz and I are both trying to define custom algebra with some custom symbols and custom operators, and we are patching parse and such, but in the end the approach feels not right.

In my case FWIW, this is to support SPDX license expressions http://spdx.org/sites/spdx/files/SPDX-2.0.pdf#page=81&zoom=auto,-46,738 for https://github.com/nexB/scancode-toolkit 

I should be able to define an algebra with:
* the symbol class I want, 
* what are the operators and (separators) strings I want to use for parsing, str and repr,
* eventually provide my own tokenization 

With that set, everything else would flow nicely. And today it does not. 

And frankly I cannot fathom what to make of and I would use this https://github.com/bastikr/boolean.py/blob/cf68b5644c4b3c2fef25733acd6ef3ebe4d60901/boolean/boolean.py#L1105

**Comment by bastikr** [comment]
The things that you referenced first i.e.

```python
# A boolean algebra is defined by its base elements (=domain), its operations
# (in this case only NOT, AND and OR) and an additional "symbol" type.
Algebra = collections.namedtuple("Algebra",
                                 ("domain", "operations", "symbol"))

# Defines the two base elements TRUE and FALSE for the algebra.
BooleanDomain = collections.namedtuple("BooleanDomain", ("TRUE", "FALSE"))

# Defines the basic boolean operations NOT, AND and OR.
BooleanOperations = collections.namedtuple("BooleanOperations",
                                           ("NOT", "AND", "OR"))
```

allow you to redefine all the elements of the Boolean algebra. This can't be done with inheritance since for example if you want to redefine the AND class then sub-classing it won't help because the operation `a & b` defined between two symbols doesn't know that it should use the new AND type. The way to use it is at the moment is a bit lacking since one has to dynamically set the class variable Expression.algebra as it is done here

```python
# Create a default algebra.
DOMAIN = BooleanDomain(TRUE=TRUE, FALSE=FALSE)
OPERATIONS = BooleanOperations(NOT=NOT, AND=AND, OR=OR)
ALGEBRA = Algebra(DOMAIN, OPERATIONS, Symbol)
Expression.algebra = ALGEBRA
```

for the default algebra.

Changing class variables is a tricky and not recommended thing to do since it means that there is no simple way to use two boolean algebras in parallel. Especially bad is this if two separate projects rely on this module. If one of them changes something it will influence the other one in unpredictable ways. However, it's simple and straightforward and will probably be enough for most use cases. As you noticed this feature is not well tested, e.g. the parse function doesn't make use of custom algebras. There is definitely room for improvement.

I will try to explain the BooleanAlgebra class later on - I'm just a bit tired after a whole day of skiing:)

**Comment by pombredanne** [comment]
@bastikr you wrote:
>The things that you referenced first [...] allow you to redefine all the elements of the Boolean algebra. 

Quite frankly I cannot fathom any use case where these would need to be redefined for a sane purpose from the standard algebra.

The customization that I think are important are:
- custom Symbol / boolean variable classes
- custom operations and parens strings for parsing and serialization back to a string
- custom parsing by feeding pre-tokenized streams.

So IMHO some of these should not be class members, but part of some algebra config objects of sorts, with a provided default.  
Other customizations are likely impractical IMHO.

**Comment by Kronuz** [comment]
Was this intended for adding XOR, NAND and other operators to an algebra? I saw this just yesterday when I was heading into adding `symbol_class` to `symbols()`.

**Comment by bastikr** [comment]
Yes originally I wanted to support any possible (complete) combination of boolean operators.

**Comment by Kronuz** [comment]
BooleanAlgebra class is never used, only Algebra named tuple. I vote for refactoring this bits; but I propose first closing all other remaining issues and pull requests first. Particularly the new tokenizer, but `bool()` as well.

**Comment by bastikr** [comment]
The idea behind the BooleanAlgebra is the following. As an example let's say we want to implement a system that allows us to select entries that fulfill certain conditions from a list that stores many different types of information - name, date of birth, GPS-coordinates, and so on. We let the user define criteria (Symbols) and allow them to combine them in any way they want (Boolean Operations). Finally we want to use the resulting expression to test each entry in the list. A nice way to break down the code is to write a separate class for every type of criterion, let's say one to test birthday dates and another one to check if GPS coordinates are in a certain area but all of them have in common that they define a method `test_condition` that takes an entry from the list and returns True or False.

So think about how you would use boolean.py to implement the boolean logic behind these criterions. A first idea might by to let all these classes inherit from Symbol. But combining them will then result in an AND or an OR object which both don't define the desired `test_condition` function. Of course there are several possibilities to remedy this and maybe you can think of a really elegant solution. The result I came up with is the BooleanAlgebra class which can be used as super-class of all criterion classes and then provides the correct behavior.

This is only the general outline but hopefully conveys the idea well enough without going into too much detail. I still think the concept is sound but maybe we can come up with a better solution for this problem. This was btw more or less the original motivation I had for this project but I got distracted and never really used it.

**Comment by pombredanne** [comment]
@bastikr Unless you have an existing need for this `BooleanAlgebra` class I would like to remove it for now. with #33 the design would become clearer IMHO and this will be a non issue.

**Comment by bastikr** [comment]
I don't see why #33 solves the same problem as the BooleanAlgebra class. But anyway its use case seams to be too cryptic so it's probably better to just remove it.

**Comment by pombredanne** [comment]
BooleanAlgebra removed for now. Closing
