### ISSUE TITLE
Custom representation of an expression

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#36]
I would like to be able to represent an expression as a string with the boolean operators I want and not the default `+` and `*`.

**Comment by bastikr** [comment]
I see a few possibilities:

* The dirty hack: just dynamically rename the operator class variable of OR and AND.
* The roundabout: Subclass them, override operator and redefine the algebra with the new classes. For this to work we have to overhaul the whole changing algebra thing which would be a good thing to do anyway. 
* The overkill: Implement a Printer class like sympy does: https://github.com/sympy/sympy/blob/master/sympy/printing/printer.py

Thoughts?

**Comment by pombredanne** [comment]
IMHO, 2. the roundabout

**Comment by pombredanne** [comment]
Also the operators strings should likely NOT be class level, but instance level

**Comment by pombredanne** [comment]
IMHO the key issue is the fact that the default algebra is a global:
https://github.com/bastikr/boolean.py/blob/ae55534c32bdcd6edf1e8795295a3e5d414cd54b/boolean/boolean.py#L967
https://github.com/bastikr/boolean.py/blob/ae55534c32bdcd6edf1e8795295a3e5d414cd54b/boolean/boolean.py#L62

**Comment by Kronuz** [comment]
@pombredanne, I agree. Operator string could be instance level; and it could be initialized to use the same `token_string` used during parsing, maybe. Although this would mean the printed representation could have mixed operator strings; i.e. `"a + b * c & d | e"`, after parsing, printing it as string would output the same string.

**Comment by pombredanne** [comment]
@Kronuz FWIW in #41, the operators are at the instance level, though they are not meant to be customized yet. But they could... and eventually they could be collected from the parsing then. Though as you pointed out, this would become eventually weird.

**Comment by pombredanne** [comment]
in #41 types can be fully subclassed and customized for a given algebra. This allow any custom representation and stringification of expressions. I am closing this
