### ISSUE TITLE
Symbol requires 'object' (of the constructor) to implement __lt__, __gt__, etc.

### ISSUE THREAD

**Issue by 5nizza** [bastikr/boolean.py#4]
Here is the traceback that reveals that for Symbol(object) constructor to be usable the constructor object should implement __lt__ (and probably others comparison operators)
(I raise RuntimeError when __lt__ is called in my object):

    Traceback (most recent call last):
      expr = (expr * s) if val else (expr * ~s)
    File "boolean.py", line 245, in __mul__
      return self.algebra.operations.AND(self, other)
    File "boolean.py", line 462, in __new__
      return cls(*args, eval=False).eval()
    File "boolean.py", line 797, in eval
      args.sort()
    File "boolean.py", line 240, in __gt__
      return not self.__lt__(other)
    File "boolean.py", line 596, in __lt__
      return self.args[0].__lt__(other)
    File "boolean.py", line 426, in __lt__
      return self.obj.__lt__(other.obj) # 2 named symbols.
    File "parser_expr.py", line 45, in __lt__
      raise RuntimeError()

The problem is that if you do not implement `__lt__`, etc. then the default `__lt__` is used -- and this can result in the wrong result when normalize boolean expressions to dnf.
Let me know if you need a complete example revealing this.
Regards,)

**Comment by pombredanne** [comment]
@5nizza do you have a concrete example for this?

**Comment by Kronuz** [comment]
Yes, this is an issue I also fixed on my pull request

**Comment by bastikr** [comment]
This is fixed now in the master branch.
