### ISSUE TITLE
Use `&` and `|` as default AND and OR operators

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#40]
Using + and * may be correct mathematically but is utterly confusing when programming.
As a programmer I want simple and intuitive. We should make  `&` and `|`  the default AND and OR operators respectively.

**Comment by pombredanne** [comment]
@Kronuz @bastikr any feedback on this?

**Comment by pombredanne** [comment]
I would really like to implement this as defaults. I strongly feels this is a serious barrier to adoption.

**Comment by pombredanne** [comment]
@bastikr @Kronuz Since there is no objection, I would like to make it part of version 2.0 and update the doc and tests accordingly. I will go ahead after I have merged #41

**Comment by Kronuz** [comment]
I concur regarding using `&` and `|` as the defaults.

**Comment by pombredanne** [comment]
Fixed and merged  develop
