### ISSUE TITLE
Enable Travis

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#42]
@bastikr could you enable Travis so we get continuous builds?
https://travis-ci.org/bastikr/boolean.py
I committed a basic travis config with https://github.com/bastikr/boolean.py/commit/fa12f8eb5720bf66af7682532ff99f0c7f99fee5

**Comment by pombredanne** [comment]
@bastikr Note that if you give me the admin rights on this repo, I will be able to enable the travis service integration.

**Comment by pombredanne** [comment]
@bastikr On travis I get this:
```
This is not an active repository

You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself.
```

I would need to have admin rights on the repo to enable this. Do you mind to set this up?
Thanks!

**Comment by pombredanne** [comment]
@bastikr Would you prefer that I maintain a stable fork elsewhere?

**Comment by bastikr** [comment]
I'm so sorry that I missed this issue. I enabled testing for boolean.py on my travis profile - it should trigger for the next push. Do you know how I can give you the appropriate rights to do things like this in the future? Alternatively, do you think it's a good idea to move to a github organization?

**Comment by Kronuz** [comment]
In my opinion, there is no need for an organization, as this is just a single project... that's my opinion.

**Comment by pombredanne** [comment]
@bastikr Thanks! enabling travis should be fine for now :)
Thanks!
I will update the readme to put a badge to https://travis-ci.org/bastikr/boolean.py

**Comment by pombredanne** [comment]
And we have our first build that ran and passed on 2.7, 3.4 and 3.5 .... This will keep us honest!
https://travis-ci.org/bastikr/boolean.py/builds/190951931

Thanks. Closing now.

**Comment by Kronuz** [comment]
Great! Thank you @pombredanne !
