### ISSUE TITLE
Who is using boolean.py?

### ISSUE THREAD

**Issue by pombredanne** [bastikr/boolean.py#55]
I would like to collect this so we can either put this in a wiki page or the README.
I do use it in this project https://github.com/nexB/license-expression/ eventually reused in many other places.

 @Kronuz @bastikr what do you think? How and where do you use it?

**Comment by pombredanne** [comment]
@5nizza uses it in https://github.com/5nizza/Party
@qqii uses it in https://github.com/qqii/logic-gate-simulator

**Comment by Kronuz** [comment]
My company uses it for evaluation of roles, to check access to Views and APIs. For instance we configure access that needs "foo" or "bar" but not "baz" and then users get a set of roles.

**Comment by bastikr** [comment]
I don't use it at all anymore, which explains why my contributions in the last years are a rather rare occurrence.

**Comment by pombredanne** [comment]
Closing this. This is there for the reference.
