### ISSUE TITLE
get_symbols() for NOT expression

### ISSUE THREAD

**Issue by balrok** [bastikr/boolean.py#59]
Not sure if this a bug or not, but:
```python
>>> alg = boolean.BooleanAlgebra()
>>> alg.parse("A").get_symbols()
[Symbol('A')]
>>> alg.parse("~A").get_symbols()
[]
>>> alg.parse("~A|B").get_symbols()
[Symbol('B')]
>>> alg.parse("~(A|B)").get_symbols()
[Symbol('A'), Symbol('B')]
```

So the literal NOT(A) is not retrieved by get_symbols

**Comment by pombredanne** [comment]
Thank you for the report ... hum.... I wonder if this is a bug or not, but it looks like one or at least a very confusing and surprising behavior.

**Comment by pombredanne** [comment]
I think this is a bug:
`Symbol` are only returned if `isliteral` and this is a `Symbol` instance per https://github.com/bastikr/boolean.py/blob/4903f4e7705b576fea3eccacc9c49fe870bcd10b/boolean/boolean.py#L530

And a `NOT` function is set to be a literal itself if its (single) `arg` is itself a literal per https://github.com/bastikr/boolean.py/blob/4903f4e7705b576fea3eccacc9c49fe870bcd10b/boolean/boolean.py#L921

... which would be `True` in the case of `~A` . e.g. This means `NOT` is a literal. But `NOT` is not a `Symbol` ...

And  by this faulty construction, the `NOT` function with a single symbol is therefore a literal and not a `Symbol` instance: therefore its underlying symbol is never returned with `get_symbols()`


@bastikr @Kronuz would you agree this is a bug? I think we should we return the underlying `Symbol` correctly.

**Comment by pombredanne** [comment]
@balrok Can you give a try to the latest master that contains @YaronK patches?

**Comment by balrok** [comment]
I have no extensive test-suite but it looks fine here.. I removed my hack on to of boolean and it works as expected.
Thank you :)

**Comment by pombredanne** [comment]
@balrok thank you for following up after all.... this is much appreciated!
