### ISSUE TITLE
Symbol.__lt__ assumes the class of some_symbol.obj implements __lt__

### ISSUE THREAD

**Issue by gemerden** [bastikr/boolean.py#75]
This is a small issue, i wouldn't say anything if it didn't happen to me ;-)
```
    def __lt__(self, other):
        comparator = Expression.__lt__(self, other)
        if comparator is not NotImplemented:
            return comparator
        if isinstance(other, Symbol):
            return self.obj < other.obj   # <= this might raise exception
        return NotImplemented
```
could be more robust (probably, can't oversee all the consequences), with:
```
    def __lt__(self, other):
        comparator = Expression.__lt__(self, other)
        if comparator is not NotImplemented:
            return comparator
        if isinstance(other, Symbol):
            try:
                return self.obj < other.obj
            except Exception:
                return NotImplemented
        return NotImplemented
```
This is called in simplify. For now i will override Symbol.__lt__ in my code.

Cheers, Lars

**Comment by pombredanne** [comment]
Looking good. Care for sending a PR may be with a small test case?

**Comment by gemerden** [comment]
Sure, but i have no experience with PR's. I think i need to be a collaborator to publish a branch, can you make me one?

**Comment by gemerden** [comment]
i tried some more and stadard object without __lt__ somewhere are hard to find, also it was complex to write a good test (since i think at least some python versions fall back to `not __gt__` or some such. Due to rarity of problem and it was taking me too much time, i withdraw the issue ...
