### ISSUE TITLE
Rename package to make it play well with dev tools

### ISSUE THREAD

**Issue by fkromer** [bastikr/boolean.py#97]
The name of this package (`boolean.py`) is unconventional. This leads to problems when using common Python dev tools. E.g. running [`liccheck`](https://pypi.org/project/liccheck/) with `$ liccheck -s license_check.ini -r requirements.txt` leads to `pkg_resources.DistributionNotFound: The 'boolean-py==3.7' distribution was not found and is required by the application`

**Comment by pombredanne** [comment]
@fkromer I reckon that's a little bit uncommon, but this is still valid for a package name to have a dot and a dot py extension
Which Python/pip/setuptools version do you run and on which OS?

**Comment by pombredanne** [comment]
Actually your issue stems from not using the package name:
use `boolean.py==3.7` and not `boolean-py==3.7`
