### ISSUE TITLE
Incorrect SPDX identifier in boolean/__init__.py

### ISSUE THREAD

**Issue by zyga** [bastikr/boolean.py#99]
The file mentions:
```
SPDX-License-Identifier: BSD-3-Clause
```
But the rest of the source says:
```
SPDX-License-Identifier: BSD-2-Clause
```
which actually agrees with the `LICENSE.txt` file.

**Comment by pombredanne** [comment]
@zyga Thanks and good catch... that's a little bit of a cobbler's son problem I reckon :|

**Comment by pombredanne** [comment]
Thanks! this has been fixed.
